SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE FROM ANIMAL_INS;

-- SELECT ANIMAL_TYPE, 
-- (CASE
-- WHEN NAME IS NULL THEN 'No name'
-- WHEN NAME IS NOT NULL THEN NAME
-- END) AS NAME
-- , SEX_UPON_INTAKE FROM ANIMAL_INS;