WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM CTE WHERE HOUR < 23
)

SELECT CTE.HOUR, COUNT(ANIMAL_OUTS.ANIMAL_ID) 
FROM CTE
LEFT JOIN ANIMAL_OUTS 
ON CTE.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY CTE.HOUR;